/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Model.Person;



/**
 *
 * @author harish
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    private Person person;
    public UI() {
        initComponents();
        
        this.person= new Person();
      
    }
    
    public UI(Person personreceipe) {
        this.setVisible(true);
        initComponents();
        
        this.person = personreceipe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlJP = new javax.swing.JPanel();
        createB = new javax.swing.JButton();
        viewB = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        displayJP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlJP.setBackground(new java.awt.Color(255, 204, 204));

        createB.setBackground(new java.awt.Color(204, 204, 204));
        createB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        createB.setText("Create");
        createB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBActionPerformed(evt);
            }
        });

        viewB.setBackground(new java.awt.Color(204, 204, 204));
        viewB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        viewB.setText("View");
        viewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBActionPerformed(evt);
            }
        });

        Update.setBackground(new java.awt.Color(204, 204, 204));
        Update.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlJPLayout = new javax.swing.GroupLayout(controlJP);
        controlJP.setLayout(controlJPLayout);
        controlJPLayout.setHorizontalGroup(
            controlJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(controlJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Update))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        controlJPLayout.setVerticalGroup(
            controlJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlJPLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(createB)
                .addGap(54, 54, 54)
                .addComponent(Update)
                .addGap(57, 57, 57)
                .addComponent(viewB)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(controlJP);

        displayJP.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout displayJPLayout = new javax.swing.GroupLayout(displayJP);
        displayJP.setLayout(displayJPLayout);
        displayJPLayout.setHorizontalGroup(
            displayJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        displayJPLayout.setVerticalGroup(
            displayJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(displayJP);

        getContentPane().add(SplitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBActionPerformed
        // TODO add your handling code here:
        SplitPane.setRightComponent(new View(this.person));
    }//GEN-LAST:event_viewBActionPerformed

    private void createBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBActionPerformed
        // TODO add your handling code here:
        SplitPane.setRightComponent(new createJP(this.person));
    }//GEN-LAST:event_createBActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        System.out.println("Interface.UI.UpdateActionPerformed()");
        SplitPane.setRightComponent(new Update(this.person));
       
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton Update;
    private javax.swing.JPanel controlJP;
    private javax.swing.JButton createB;
    private javax.swing.JPanel displayJP;
    private javax.swing.JButton viewB;
    // End of variables declaration//GEN-END:variables
}
