/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Applicant;
import Model.Business;
import Model.Insurance;
import javax.swing.DefaultCellEditor;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ghostdaddy16
 */
public class AssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Assign
     */Business business;
        Insurance insurance;
        Applicant applicant;
    public AssignJPanel(Business business) {
        initComponents();
        this.business=business;
        populatetable();
        populateinsurancebox();
    }
    public void populatetable(){
            DefaultTableModel model= (DefaultTableModel )tblinfo.getModel();
           // TableColumn insurancecolumn=model.getColumnModel.getColumn(5);
            model.setRowCount(0);
            
        for(Applicant  io : business.getApplicantdirrectory().getApplicantlist()){
            Object[]row =new Object[11];
           row[0]=io;
            row[1]=io.getLn();
            row[2]=io.getAid();
            row[3]=io.getPet().getPn();
            row[4]=io.getPet().getType();
            row[5]=io.getPet().getBreed();
            row[6]=io.getPet().getGender();
            row[7]=io.getPet().getAge();
            row[8]=io.getPet().getVaccine().getVn();
            row[9]=io.getPet().getVaccine().getCc();
            
            
            model.addRow(row);
        }
                
    }
    private void search(String str){
        DefaultTableModel model= (DefaultTableModel )tblinfo.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        tblinfo.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str ));
    }
    public void populateinsurancebox(){
        for(Insurance i: this.business.getInsurancedirectory().getInsurancelist()){
           comboboxinsurance.addItem(String.valueOf(i.getIid()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinfo = new javax.swing.JTable();
        comboboxinsurance = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 114, 30));

        tblinfo.setBackground(new java.awt.Color(255, 255, 204));
        tblinfo.setForeground(new java.awt.Color(255, 0, 0));
        tblinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "FIRST NAME", " LASTNAME", "APPLICANT ID", "PET NAME", "PET TYPE", "PET BREED", "PET GENDER", "PET AGE", "VACCINE NAME", "VACCINE STATUS", "INSURANCE"
            }
        ));
        jScrollPane1.setViewportView(tblinfo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1130, 180));

        add(comboboxinsurance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 50, 30));

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        jLabel1.setText("Search :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 80, 20));

        jLabel2.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        jLabel2.setText("Select an Insurance Plan :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 140, 30));

        jLabel3.setText("Plan Id:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arima Madurai", 3, 18)); // NOI18N
        jLabel4.setText("Assign Insurance Plan");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 370, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //get the insurance object from combobox
        int iid=Integer.parseInt(comboboxinsurance.getSelectedItem().toString());
        //find the insurance object from business class
        Insurance insurance=business.findInsurance(iid);
                //getting the applicatiant object to set his pet insurance
                int selectedRowIndex=tblinfo.getSelectedRow();
                int id=Integer.parseInt(tblinfo.getValueAt(selectedRowIndex, 2).toString());
                 Applicant applicant=this.business.findApplicant(id);
                 this.applicant=applicant;
                 applicant.getPet().setInsurance(insurance);
        //setting the value of insurance to table
                DefaultTableModel model= (DefaultTableModel )tblinfo.getModel();
                model.setValueAt(insurance.getPlanname(), selectedRowIndex, 10);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String searchstring= txtsearch.getText();
        search(searchstring);
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxinsurance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinfo;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
